import 'dart:convert';
import 'dart:io';

Future<void> main() async {
  final configFile = File('.dart_tool/package_config.json');
  if (!configFile.existsSync()) {
    stderr.writeln('Run "flutter pub get" before generating notices.');
    exitCode = 1;
    return;
  }

  final config =
      jsonDecode(await configFile.readAsString()) as Map<String, dynamic>;
  final packages =
      (config['packages'] as List<dynamic>)
          .cast<Map<String, dynamic>>()
          .where((package) => package['name'] != 'jamhorse')
          .toList()
        ..sort(
          (left, right) =>
              (left['name'] as String).compareTo(right['name'] as String),
        );

  final output = StringBuffer()
    ..writeln('# Third-party notices')
    ..writeln()
    ..writeln(
      'Generated by `dart run tool/generate_third_party_notices.dart` from '
      'the dependency graph resolved in `pubspec.lock`.',
    )
    ..writeln()
    ..writeln(
      'JamHorse is an independent Jellyfin client and is not affiliated with '
      'or endorsed by the Jellyfin project.',
    );
  final licenseOwners = <String, String>{};

  for (final package in packages) {
    final name = package['name'] as String;
    final root = Directory.fromUri(
      configFile.uri.resolve(package['rootUri'] as String),
    );
    final pubspec = File.fromUri(root.uri.resolve('pubspec.yaml'));
    final version = await _readVersion(pubspec);
    final license = await _findLicense(root);

    output
      ..writeln()
      ..writeln('---')
      ..writeln()
      ..writeln('## $name${version == null ? '' : ' $version'}')
      ..writeln();

    if (license == null) {
      output.writeln(
        'No standalone license file was found in the resolved package. '
        'Consult the package source recorded in `pubspec.lock`.',
      );
    } else {
      final licenseText = (await license.readAsString())
          .split(RegExp(r'\r?\n'))
          .map((line) => line.trimRight())
          .join('\n')
          .trim();
      final existingOwner = licenseOwners[licenseText];
      if (existingOwner != null) {
        output.writeln(
          'Uses the same license text reproduced under `$existingOwner`.',
        );
        continue;
      }
      licenseOwners[licenseText] = name;
      output
        ..writeln('Source license file: `${license.uri.pathSegments.last}`')
        ..writeln()
        ..writeln('```text')
        ..writeln(licenseText)
        ..writeln('```');
    }
  }

  await File('THIRD_PARTY_NOTICES.md').writeAsString(output.toString());
}

Future<String?> _readVersion(File pubspec) async {
  if (!pubspec.existsSync()) return null;
  for (final line in await pubspec.readAsLines()) {
    final match = RegExp(r'^version:\s*([^\s+#]+)').firstMatch(line);
    if (match != null) return match.group(1);
  }
  return null;
}

Future<File?> _findLicense(Directory packageRoot) async {
  final directories = <Directory>[
    packageRoot,
    packageRoot.parent,
    packageRoot.parent.parent,
  ];
  const preferredNames = <String>[
    'license',
    'license.md',
    'license.txt',
    'copying',
    'copying.md',
    'copying.txt',
    'notice',
    'notice.md',
    'notice.txt',
  ];

  for (final directory in directories) {
    if (!directory.existsSync()) continue;
    final files = directory
        .listSync(followLinks: false)
        .whereType<File>()
        .toList();
    for (final preferredName in preferredNames) {
      for (final file in files) {
        final name = file.uri.pathSegments.last.toLowerCase();
        if (name == preferredName) return file;
      }
    }
  }
  return null;
}
